// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file assets/cursor-tab.proto (package aiserver.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

// @version: 1.6.14
// @author: wisdgod <nav@wisdgod.com>
// @license: MIT OR Apache-2.0

import { AddTabRequestToEvalRequest, AddTabRequestToEvalResponse, AvailableCppModelsRequest, AvailableCppModelsResponse, CppAppendRequest, CppAppendResponse, CppConfigRequest, CppConfigResponse, CppEditHistoryStatusRequest, CppEditHistoryStatusResponse, CursorPredictionConfigRequest, CursorPredictionConfigResponse, EditHistoryAppendChangesRequest, EditHistoryAppendChangesResponse, FSConfigRequest, FSConfigResponse, FSGetFileContentsRequest, FSGetFileContentsResponse, FSGetMultiFileContentsRequest, FSGetMultiFileContentsResponse, FSIsEnabledForUserRequest, FSIsEnabledForUserResponse, FSSyncFileRequest, FSSyncFileResponse, FSUploadFileRequest, FSUploadFileResponse, GetCppEditClassificationRequest, GetCppEditClassificationResponse, IsCursorPredictionEnabledRequest, IsCursorPredictionEnabledResponse, MarkCppRequest, MarkCppResponse, RecordCppFateRequest, RecordCppFateResponse, RefreshTabContextRequest, RefreshTabContextResponse, ShouldTurnOnCppOnboardingRequest, ShouldTurnOnCppOnboardingResponse, StreamCppRequest, StreamCppResponse, StreamHoldCppRequest, StreamHoldCppResponse, StreamNextCursorPredictionRequest, StreamNextCursorPredictionResponse } from "./cursor-tab_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * .aiserver.v1.FileSyncService
 *
 * @generated from service aiserver.v1.FileSyncService
 */
export const FileSyncService = {
  typeName: "aiserver.v1.FileSyncService",
  methods: {
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.FileSyncService.FSUploadFile
     */
    fSUploadFile: {
      name: "FSUploadFile",
      I: FSUploadFileRequest,
      O: FSUploadFileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.FileSyncService.FSSyncFile
     */
    fSSyncFile: {
      name: "FSSyncFile",
      I: FSSyncFileRequest,
      O: FSSyncFileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.FileSyncService.FSIsEnabledForUser
     */
    fSIsEnabledForUser: {
      name: "FSIsEnabledForUser",
      I: FSIsEnabledForUserRequest,
      O: FSIsEnabledForUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.FileSyncService.FSConfig
     */
    fSConfig: {
      name: "FSConfig",
      I: FSConfigRequest,
      O: FSConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.FileSyncService.FSGetFileContents
     */
    fSGetFileContents: {
      name: "FSGetFileContents",
      I: FSGetFileContentsRequest,
      O: FSGetFileContentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.FileSyncService.FSGetMultiFileContents
     */
    fSGetMultiFileContents: {
      name: "FSGetMultiFileContents",
      I: FSGetMultiFileContentsRequest,
      O: FSGetMultiFileContentsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * .aiserver.v1.CppService
 *
 * @generated from service aiserver.v1.CppService
 */
export const CppService = {
  typeName: "aiserver.v1.CppService",
  methods: {
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.CppService.MarkCppForEval
     */
    markCppForEval: {
      name: "MarkCppForEval",
      I: MarkCppRequest,
      O: MarkCppResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ServerStreaming
     *
     * @generated from rpc aiserver.v1.CppService.StreamHoldCpp
     */
    streamHoldCpp: {
      name: "StreamHoldCpp",
      I: StreamHoldCppRequest,
      O: StreamHoldCppResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.CppService.AvailableModels
     */
    availableModels: {
      name: "AvailableModels",
      I: AvailableCppModelsRequest,
      O: AvailableCppModelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.CppService.RecordCppFate
     */
    recordCppFate: {
      name: "RecordCppFate",
      I: RecordCppFateRequest,
      O: RecordCppFateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.CppService.AddTabRequestToEval
     */
    addTabRequestToEval: {
      name: "AddTabRequestToEval",
      I: AddTabRequestToEvalRequest,
      O: AddTabRequestToEvalResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * .aiserver.v1.AiService
 *
 * @generated from service aiserver.v1.AiService
 */
export const AiService = {
  typeName: "aiserver.v1.AiService",
  methods: {
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.AiService.ShouldTurnOnCppOnboarding
     */
    shouldTurnOnCppOnboarding: {
      name: "ShouldTurnOnCppOnboarding",
      I: ShouldTurnOnCppOnboardingRequest,
      O: ShouldTurnOnCppOnboardingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ServerStreaming
     *
     * @generated from rpc aiserver.v1.AiService.StreamCpp
     */
    streamCpp: {
      name: "StreamCpp",
      I: StreamCppRequest,
      O: StreamCppResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.AiService.CppConfig
     */
    cppConfig: {
      name: "CppConfig",
      I: CppConfigRequest,
      O: CppConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.AiService.CppEditHistoryStatus
     */
    cppEditHistoryStatus: {
      name: "CppEditHistoryStatus",
      I: CppEditHistoryStatusRequest,
      O: CppEditHistoryStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.AiService.CppAppend
     */
    cppAppend: {
      name: "CppAppend",
      I: CppAppendRequest,
      O: CppAppendResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.AiService.RefreshTabContext
     */
    refreshTabContext: {
      name: "RefreshTabContext",
      I: RefreshTabContextRequest,
      O: RefreshTabContextResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ServerStreaming
     *
     * @generated from rpc aiserver.v1.AiService.StreamNextCursorPrediction
     */
    streamNextCursorPrediction: {
      name: "StreamNextCursorPrediction",
      I: StreamNextCursorPredictionRequest,
      O: StreamNextCursorPredictionResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.AiService.IsCursorPredictionEnabled
     */
    isCursorPredictionEnabled: {
      name: "IsCursorPredictionEnabled",
      I: IsCursorPredictionEnabledRequest,
      O: IsCursorPredictionEnabledResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.AiService.GetCppEditClassification
     */
    getCppEditClassification: {
      name: "GetCppEditClassification",
      I: GetCppEditClassificationRequest,
      O: GetCppEditClassificationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.AiService.CppEditHistoryAppend
     */
    cppEditHistoryAppend: {
      name: "CppEditHistoryAppend",
      I: EditHistoryAppendChangesRequest,
      O: EditHistoryAppendChangesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * .aiserver.v1.CursorPredictionService
 *
 * @generated from service aiserver.v1.CursorPredictionService
 */
export const CursorPredictionService = {
  typeName: "aiserver.v1.CursorPredictionService",
  methods: {
    /**
     * Unary
     *
     * @generated from rpc aiserver.v1.CursorPredictionService.CursorPredictionConfig
     */
    cursorPredictionConfig: {
      name: "CursorPredictionConfig",
      I: CursorPredictionConfigRequest,
      O: CursorPredictionConfigResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

